.github/workflows/test.yaml vernejen

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -14,7 +14,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - name: Generate an Error
-      run: test 5 -eq 5
+      run: test 5 -eq 42
 
   this_always_fails_1:
     runs-on: ubuntu-latest
@@ -23,6 +23,5 @@ jobs:
       run: echo "Hello World"
     - name: Error out
       run: |
-        echo "No error for this PR!"
-        sleep 4m
-        exit 0
+        echo "Error!!!"
+        exit 1
